### ISSUE TITLE
Color scheme turned to light

### ISSUE THREAD

**Issue by insssomniac** [Dj0ulo/OptiSearch#39]
Hi,

I noticed that color scheme turned to white and i can't see almost anything. Is there any way to change it?

![image](https://github.com/Dj0ulo/OptiSearch/assets/42058438/39844090-b038-4a2e-936d-32945c19e223)

**Comment by Dj0ulo** [comment]
Hi,
Thanks for the feedback!
Could you tell me what browser you are using, as well as the search engine (if it is google, is it google.com or another one domain like google.fr?)

Could you maybe right click on the page, save the html and send me this file here so that I can investigate more.

Thank you!

**Comment by insssomniac** [comment]
Hi,
It is Chrome Version 123.0.6312.58 (Official Build) (64-bit) and google search engine (google.com). When I inspect the elements, I noticed that it applied dark theme to the plugin, and when I removed dark class, everything was fine. But I see you fixed it already and now it looks properly. Thanks!
