### ISSUE TITLE
feat: One time payment for premium

### ISSUE THREAD

**Issue by CodeF53** [Dj0ulo/OptiSearch#45]
I despise subscriptions and won't buy the $1/m premium, because I know I will forget I own it and pay it for the rest of my life.

Could we get an alternate method were we make a one time payment of $10-$30?

Otherwise I'm just going to donate to you and [patch the extension to think I have premium](https://hastebin.com/share/motexeqexi.diff)

**Comment by Dj0ulo** [comment]
It's a little delicate for me to offer lifetime access plan.

Since those extensions rely on third-party services I constantly need to maintain them to keep up with their respective updates and I know I will probably stop doing that at some point in the future.


However I can do an exception for you if you really don't want to pay a monthly fee.

If you send me 20€ on [paypal](https://www.paypal.com/donate?hosted_button_id=VPF2BYBDBU5AA) and your email address, I can add it to the list of permanent premium users.


This way you will get the premium subscription forever until I stop supporting it.

**Comment by CodeF53** [comment]
That donate link keeps giving me a vauge error when I try sending with it? Can I get your PayPal email so I can send it directly?

**Comment by Dj0ulo** [comment]
It's:
julien.launois99@gmail.com

Thank you, it means a lot!

**Comment by CodeF53** [comment]
Sent

**Comment by Dj0ulo** [comment]
Thanks! Could you please give me an email address so that I can register it as premium?
